-- =====================================================
-- wecreate 数据库建库建表脚本
-- 创建数据库：wecreate
-- 包含表：WECREATE_CLI_LOG, WECREATE_CLI_PROMPT, WECREATE_PROJECT
-- =====================================================

-- 创建数据库
CREATE DATABASE IF NOT EXISTS `wecreate` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `wecreate`;

-- =====================================================
-- 表：WECREATE_CLI_LOG
-- 描述：自定义日志追踪表
-- =====================================================
DROP TABLE IF EXISTS `WECREATE_CLI_LOG`;

CREATE TABLE `WECREATE_CLI_LOG` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CREATE_USER` VARCHAR(50) NOT NULL,
  `CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `TRACE_ID` VARCHAR(255) NOT NULL,
  `TYPE` VARCHAR(255) NOT NULL,
  `CONTENT` LONGTEXT,
  `LM_USER` VARCHAR(50),
  `LM_TIME` TIMESTAMP NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='自定义日志追踪表';

-- 添加列注释
ALTER TABLE `WECREATE_CLI_LOG` MODIFY COLUMN `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `WECREATE_CLI_LOG` MODIFY COLUMN `CREATE_USER` VARCHAR(50) NOT NULL COMMENT '创建人';
ALTER TABLE `WECREATE_CLI_LOG` MODIFY COLUMN `CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间';
ALTER TABLE `WECREATE_CLI_LOG` MODIFY COLUMN `TRACE_ID` VARCHAR(255) NOT NULL COMMENT '追踪标识';
ALTER TABLE `WECREATE_CLI_LOG` MODIFY COLUMN `TYPE` VARCHAR(255) NOT NULL COMMENT '日志类型';
ALTER TABLE `WECREATE_CLI_LOG` MODIFY COLUMN `CONTENT` LONGTEXT COMMENT '日志内容';
ALTER TABLE `WECREATE_CLI_LOG` MODIFY COLUMN `LM_USER` VARCHAR(50) COMMENT '最后更新人';
ALTER TABLE `WECREATE_CLI_LOG` MODIFY COLUMN `LM_TIME` TIMESTAMP NULL COMMENT '最后更新时间';


-- =====================================================
-- 表：WECREATE_CLI_PROMPT
-- 描述：CLI 提示词执行记录表
-- =====================================================
DROP TABLE IF EXISTS `WECREATE_CLI_PROMPT`;

CREATE TABLE `WECREATE_CLI_PROMPT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `CREATE_USER` VARCHAR(50) NOT NULL,
  `CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `PROMPT_CONTENT` LONGTEXT,
  `EXECUTION_TIME` INT,
  `WORK_DIRECTORY` VARCHAR(500),
  `TRACE_ID` VARCHAR(255) NOT NULL,
  `REQUEST_IP` VARCHAR(50),
  `LM_USER` VARCHAR(50),
  `LM_TIME` TIMESTAMP NULL,
  `PROJECT_ID` VARCHAR(255),
  `SCORE` DECIMAL(3,1),
  `SCORE_USER` VARCHAR(50),
  `GIT_CHANGED_FILES` INT,
  `GIT_INSERTIONS` INT,
  `GIT_DELETIONS` INT,
  `GIT_TOTAL_CHANGES` INT,
  `DESCRIPTION` LONGTEXT,
  `INPUT_TOKENS` INT,
  `OUTPUT_TOKENS` INT,
  `TOTAL_TOKENS` INT,
  `CACHED_TOKENS` INT,
  `GIT_COMMIT_HASH` VARCHAR(100),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CLI 提示词执行记录表';

-- 添加列注释
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `CREATE_USER` VARCHAR(50) NOT NULL COMMENT '创建人';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `PROMPT_CONTENT` LONGTEXT COMMENT '提示词内容';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `EXECUTION_TIME` INT COMMENT '执行耗时 (毫秒)';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `WORK_DIRECTORY` VARCHAR(500) COMMENT '工作目录';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `TRACE_ID` VARCHAR(255) NOT NULL COMMENT '追踪标识';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `REQUEST_IP` VARCHAR(50) COMMENT '请求 IP';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `LM_USER` VARCHAR(50) COMMENT '最后更新人';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `LM_TIME` TIMESTAMP NULL COMMENT '最后更新时间';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `PROJECT_ID` VARCHAR(255) COMMENT '项目 ID';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `SCORE` DECIMAL(3,1) COMMENT '评分';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `SCORE_USER` VARCHAR(50) COMMENT '评分人';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `GIT_CHANGED_FILES` INT COMMENT 'Git 变更文件数';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `GIT_INSERTIONS` INT COMMENT 'Git 新增行数';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `GIT_DELETIONS` INT COMMENT 'Git 删除行数';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `GIT_TOTAL_CHANGES` INT COMMENT 'Git 总变更行数';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `DESCRIPTION` LONGTEXT COMMENT '描述信息';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `INPUT_TOKENS` INT COMMENT '输入 Token 数量';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `OUTPUT_TOKENS` INT COMMENT '输出 Token 数量';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `TOTAL_TOKENS` INT COMMENT '总 Token 数量';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `CACHED_TOKENS` INT COMMENT '命中缓存 Token 数量';
ALTER TABLE `WECREATE_CLI_PROMPT` MODIFY COLUMN `GIT_COMMIT_HASH` VARCHAR(100) COMMENT 'Git 提交哈希值，用于避免重复记录同一提交';


-- =====================================================
-- 表：WECREATE_PROJECT
-- 描述：项目管理表
-- =====================================================
DROP TABLE IF EXISTS `WECREATE_PROJECT`;

CREATE TABLE `WECREATE_PROJECT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `PROJECT_NAME` VARCHAR(100) NOT NULL,
  `GIT_URL` VARCHAR(500) NOT NULL,
  `LOCAL_PATH` VARCHAR(500) NOT NULL,
  `DESCRIPTION` VARCHAR(500),
  `CREATE_USER` VARCHAR(50) NOT NULL,
  `CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `LM_USER` VARCHAR(50),
  `LM_TIME` TIMESTAMP NULL,
  `STATUS` INT DEFAULT 0,
  `REMARK` VARCHAR(500),
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_project_name` (`PROJECT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='项目管理表';

-- 添加列注释
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `PROJECT_NAME` VARCHAR(100) NOT NULL COMMENT '项目名称';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `GIT_URL` VARCHAR(500) NOT NULL COMMENT 'Git 仓库地址';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `LOCAL_PATH` VARCHAR(500) NOT NULL COMMENT '本地绝对路径';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `DESCRIPTION` VARCHAR(500) COMMENT '项目描述';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `CREATE_USER` VARCHAR(50) NOT NULL COMMENT '创建人';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `LM_USER` VARCHAR(50) COMMENT '最后更新人';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `LM_TIME` TIMESTAMP NULL COMMENT '最后更新时间';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `STATUS` INT DEFAULT 0 COMMENT '项目状态：0-未克隆，1-已克隆，2-克隆失败';
ALTER TABLE `WECREATE_PROJECT` MODIFY COLUMN `REMARK` VARCHAR(500) COMMENT '备注信息';
-- 系统配置表
CREATE TABLE IF NOT EXISTS SYSTEM_CONFIG (
    ID DECIMAL(20,0) PRIMARY KEY,
    CONFIG_KEY VARCHAR(100) NOT NULL COMMENT '配置键',
    CONFIG_VALUE VARCHAR(500) COMMENT '配置值',
    DESCRIPTION VARCHAR(200) COMMENT '配置描述',
    CREATE_USER VARCHAR(50) COMMENT '创建人',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    LM_USER VARCHAR(50) COMMENT '最后更新人',
    LM_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
    UNIQUE KEY UK_CONFIG_KEY (CONFIG_KEY)
) COMMENT='系统配置表';
